import mongoose from 'mongoose';

/**
 * Task Schema - NEM-aligned educational tasks
 * Generated by AI and scheduled for publication
 */
const taskSchema = new mongoose.Schema({
    type: {
        type: String,
        enum: ['task', 'notice'],
        default: 'task'
    },
    title: {
        type: String,
        required: [true, 'El título es requerido'],
        trim: true,
        maxlength: [200, 'El título no puede exceder 200 caracteres']
    },
    content: {
        type: String,
        required: [true, 'El contenido es requerido']
    },
    description: {
        type: String,
        required: false // Fallback/summary for the rich content
    },
    subject: {
        type: String,
        required: function () { return this.type === 'task'; }, // Required only for tasks
        enum: [
            'Lenguajes',
            'Saberes y Pensamiento Científico',
            'Ética, Naturaleza y Sociedades',
            'De lo Humano y lo Comunitario'
        ]
    },
    multimedia: [{
        type: {
            type: String,
            enum: ['youtube', 'image', 'file'],
            required: true
        },
        url: {
            type: String,
            required: true
        },
        title: String
    }],
    status: {
        type: String,
        enum: ['draft', 'scheduled', 'published'],
        default: 'published'
    },
    learningObjective: {
        type: String,
        required: false
    },
    instructions: [{
        step: Number,
        text: String
    }],
    materials: [{
        type: String
    }],
    duration: {
        type: Number,
        default: 30
    },
    difficulty: {
        type: String,
        enum: ['básico', 'intermedio'],
        default: 'básico'
    },
    isCollaborative: {
        type: Boolean,
        default: true
    },
    publishDate: {
        type: Date,
        default: Date.now
    },
    isPublished: {
        type: Boolean,
        default: true
    },
    weekNumber: {
        type: Number,
        required: function () { return this.type === 'task'; } // Required only for tasks
    },
    createdBy: {
        type: mongoose.Schema.Types.ObjectId,
        ref: 'User'
    }
}, {
    timestamps: true
});

// Index for efficient queries by publish date
taskSchema.index({ publishDate: 1, isPublished: 1 });
taskSchema.index({ weekNumber: 1 });

export const Task = mongoose.model('Task', taskSchema);
export default Task;
